---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1eksfnzzecqwujyeqz2vzxv3qv7mwxr8hk4f07n4tgru75yerddgqmveq55"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1eksfnzzecqwujyeqz2vzxv3qv7mwxr8hk4f07n4tgru75yerddgqmveq55"
stores:
  yaml:
    indent: 2
