---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
spec:
  ingressClassName: internal
  rules:
    - host: "longhorn.alexieff.io"
      http:
        paths:
          - path: /
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 8000
