# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TIqVX4kL//PbLK03xcR45Fb3D9zOYCpACyYpl2bQhyc=,iv:UhsAIHz8P6Kzj4F0G1K5SUmr4MI9aShs4l7XmXIDnU0=,tag:bxM1248O8iD196JIGDs70Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eksfnzzecqwujyeqz2vzxv3qv7mwxr8hk4f07n4tgru75yerddgqmveq55
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGl5bTNYMTlXZXZYLytC
        TG1RdHZscTFjaXdadkRBdkEvaHp1Vy8xUm1JCnY3dUVkV3lLRy85dklJQnVnQVh1
        WXVaellPN1lENWVVWEVIeE1RR2xIcm8KLS0tIFRiN0lGeXpOTzNqblJLRUo3c25F
        TjZRalhzY1VTRm9ZYzd6cTVxN3BMZnMKCo9o1ThbWS81b/bVon4Ms7QL8HbQu37g
        BxyEdc0gX/D18f6NxuZpYwidWzlI/Is0f4nMoeRZyALHWJE3U5Rztw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T02:11:27Z"
  mac: ENC[AES256_GCM,data:IyKu/IVgpnzt7dnx1ZtPKznFuuJIyBUhB5540ct43ki99aCRWjbOKEh69ip4NbvbT/bTYi7eId08bWK6Rh39DMbokRF9vTzS13Xh5nqE/RWhLl1aMkxxLIEkewIbMFFtQoavSwV0K5bJEUHAALu8uBeUZu7PnUSuEBueFd8QkCg=,iv:d6Oo3+Q5hf2rTUVQoPNkUF4JwWlVj8BQtaoVkq4uFkQ=,tag:7Gx9l0rrpeTvop/ViduwFw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
