apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:onjcZ/u2HhakpOTckN036La5N1YKdVhz9q+al7QpRcVagYGapLBS+kjzyiSjpcmUfe/rdK0/8SolfnQBZJwxw0ULH86zEkDxbck=,iv:CQD2trn+eWK49X68GjN5D7z4vfngnckrZRjq0OW39C0=,tag:Q3Vj0dqO+zH7oozaR/mF4w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eksfnzzecqwujyeqz2vzxv3qv7mwxr8hk4f07n4tgru75yerddgqmveq55
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMEx4TTVvRDRMaVRXT2hD
        eURXaXRYSE1sTU1MWEtwVkl4RW1lMi9rdzJNCjBHTm1DSEZBSWZWYTF6VzIvNWZF
        ZXFuaHYvTTdEWCt3eW5ZSEovMTFGak0KLS0tIHVBT2J1NUlNTHM3ZWtReUFxVzV0
        RHBIRXBOUVYvcUxxc1pOU0k0cWlzcjQKlsl7MSuM9Qbkrs0/cVG0IoyHPHakC2Ry
        V7qNTcfLmMRThnVN1A7/wwki79vwNAPI7xJGkPHYTglM3w/6pfEDTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T02:11:27Z"
  mac: ENC[AES256_GCM,data:NE5Khw9ibGBN/NTgzKm2sm/557qOlFurJAmLsFZ3z2/NFCj7pCIYKhltKug0ZXjzZKJ12yzu+JSBBvJwoOTmIsse0AZlXLF21NZFRbLf9kI40orBfxe/kzxWF3cq8knZQLsfbF5BJR6G0hQ6IrjWHnd1u0F6wR8bwUOyS4nfSZE=,iv:pLkFD0qzZnO5oTM1NghtC441qm7xTQLk+Mnq8x+ig/c=,tag:jNrwZQTVmUdPMF4wjpannw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
