# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:le5h5tGoxQy8RoxR8foPDdSJpbdjoWdfqD7jNNSfHoXGQ+snB15G6w==,iv:ueD2VZDhsK1rADbd2D07qgruZ+6YTMLz1jYdsooxUQA=,tag:poEKemWaaC6RfycDV+2lvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eksfnzzecqwujyeqz2vzxv3qv7mwxr8hk4f07n4tgru75yerddgqmveq55
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYTAzTWhMMERMODRIZnlR
        MTlaS05xcnZFbUxVdU9hRUpOVFZqZER5Y1VnCjNyS3dEWEpVVzh1QnN4WjV6dm56
        Vm9NYmx4Tlppbktta21RcDR3bnJTc0UKLS0tIGU1NGFOTXpiRkx6eXozN085aGNU
        SUxxNzFTTkx1RFIxTkd5MUFkOEpBVlkK5qJa70+Wnq97CIfJOgEwvWb8Qwaf2nBz
        UdKe1aJH5l4FonjsGwB1oS1e2l+682ryIjLLKmKYI8NFuPJxZwqqug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-28T11:57:53Z"
  mac: ENC[AES256_GCM,data:mvMEVkDm01sdyjsvuYpH5GNWtpKMHdPNqtqNnUDvaU+1yIsQrkDFwhto7gU64kWwWAkCJvRrlu7Z+T7Nu+DGcMlmimCQsfJ3v0tW9B3ahbQTr/yo5HIGpQQA4+MktXMpbE0PG/SCUWFNck3MLfiOVvgSmoONTp/fTlGhufbX9kc=,iv:KVPLVstMrzWOTLqU3VHY3dQvwnjOKxZFAxqICW3zsJg=,tag:YyfvREyvj+s2uBdS26lh4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
